### ISSUE TITLE
How to run on HTTPS via the Runner API

### ISSUE THREAD

**Issue by andyfaizan** [DevExpress/testcafe-browser-provider-browserstack#142]
So I have a JS/TS runner setup for running tests on Browserstack. I'm using OAuth2 from Microsoft (MSAL) and now want to test the login on different devices. It works fine on some devices whereas Android (OnePlus 7T to be precise) throws the following error:

```
   1) A JavaScript error occurred on "https://mywebsite.com/".
      Repeat test actions in the browser and check the console for errors.
      If you see this error, it means that the tested website caused it. You can fix it or disable tracking JavaScript errors in TestCafe. To do the latter, enable the
      "--skip-js-errors" option.
      If this error does not occur, please write a new issue at:
      "https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md".

      JavaScript error details:
      BrowserAuthError: pkce_not_created: The PKCE code challenge and verifier could not be generated. Detail:TypeError: Cannot read property 'digest' of undefined
          at t [as constructor] (https://mywebsite.com/main.9d97b94ac6111e739d8d.esm.js:3:191299)
          at new t (https://mywebsite.com/main.9d97b94ac6111e739d8d.esm.js:3:275880)
          at Function.t.createPkceNotGeneratedError (https://mywebsite.com/main.9d97b94ac6111e739d8d.esm.js:3:276037)
          at e.<anonymous> (https://mywebsite.com/main.9d97b94ac6111e739d8d.esm.js:3:279910)
          at https://mywebsite.com/main.9d97b94ac6111e739d8d.esm.js:3:188772
          at Object.throw (https://mywebsite.com/main.9d97b94ac6111e739d8d.esm.js:3:188877)
          at s (https://mywebsite.com/main.9d97b94ac6111e739d8d.esm.js:3:187676)

      Browser: Chrome 83.0.4103.106 / Android 10
      (https://automate.browserstack.com/builds/6858d6f32c44d80db34ff2fdf5849bb09ee90f54/sessions/f66884059b3d372ae21f5e08e0818ba236e16791)
```

I read about it and since the tests are running on HTTP, it can be a candidate for a root cause of the issue. I tried doing that using the actual certs and passing them to the runner using the `sslOptions` flag but it doesn't work. Browserstack just tries to "Get URL" for around 7 minutes and then times out. Since I want the tests to run against the URL "https://mywebsite.com", I passed the URL as the first param of the `createTestCafe` function but it says that the `hostname cannot be resolved to the current machine.` What values am I supposed to pass to the function?

Here's the runner code:

```
const createTestCafe = require('testcafe');
const fs = require('fs');
const path = require('path');

const browsers = [
  'browserstack:OnePlus 7T@10.0',
];

const sslOptions = {
  cert: fs.readFileSync(path.resolve('apps/core-e2e/ssl/cert.cer')),
  key: fs.readFileSync(path.resolve('apps/core-e2e/ssl/cert.key')),
};

// run() returns failed count
const runners: Runner[] = [];

createTestCafe(undefined, undefined, undefined, sslOptions).then(
  (tc: TestCafe) => {
    browsers.forEach((browser) => {
      console.log(`create test for browser: ${browser}`);
      const runner = tc
        .createRunner()
        .tsConfigPath('apps/core-e2e/tsconfig.e2e.json')
        .src('apps/core-e2e/src/integration/*.spec.ts')
        .browsers(browser);
      runners.push(runner);
    });
    let totalFailed = 0;
    const lastRunner = runners.reduce(
      (previous: Promise<number>, curr: Runner) =>
        previous.then((failedTests) => {
          totalFailed += failedTests;
          return curr.run();
        }),
      Promise.resolve(0),
    );
    lastRunner
      .then(
        (failedTests) => {
          totalFailed += failedTests;
          if (totalFailed > 0) {
            console.error(` ${totalFailed} 👎 TESTS FAILED 👎`);
          } else {
            console.log('👏 TESTS DONE 👏');
          }
          tc.close().then(() => process.exit(totalFailed));
        },
        (error) => {
          console.error(` 👎 AN ERROR OCCURRED 👎 : ${error}`);
          tc.close().then(() => process.exit(1));
        },
      )
      .catch((error) => {
        console.error(`😱😱 SOMETHING WENT WRONG 😱😱: ${error}`);
      });
  },
);
```

Env file
```
BROWSERSTACK_ACCESS_KEY=my_access_key
BROWSERSTACK_ACCEPT_SSL_CERTS=true
BROWSERSTACK_BUILD_ID=local-testing
BROWSERSTACK_CAPABILITIES_CONFIG_PATH="apps/core-e2e/browserstack-config.json"
BROWSERSTACK_USE_AUTOMATE="1"
BROWSERSTACK_USERNAME=myusername
DOMAIN=https://mywebsite.com
```

Capabilities JSON:
```
{
  "browserstack.console": "verbose",
  "browserstack.idleTimeout": "90",
  "browserstack.networkLogs": true,
  "acceptSslCerts": true
}
```

**Comment by andyfaizan** [comment]
If this is already a known issue/has already been documented elsewhere, kindly just forward me to there. I was unable to find it in the documentation and also here in the issues list.

**Comment by andyfaizan** [comment]
Closing this as I figured it out how to do it. Passed the options as an options object.

```
createTestCafe({
  ssl: sslOptions,
  developmentMode: true,
})
```
