### ISSUE TITLE
Error: Authentication failed. Please assign the correct username and access key to the BROWSERSTACK_USERNAME and BROWSERSTACK_ACCESS_KEY environment variables.

### ISSUE THREAD

**Issue by Namtran87** [DevExpress/testcafe-browser-provider-browserstack#160]
I am working on a sample testcafe project and was trying to the testcafe test cases on BrowserStack but below error is displayed:

Using locally installed version of TestCafe.
ERROR Error: Authentication failed. Please assign the correct username and access key to the BROWSERSTACK_USERNAME and BROWSERSTACK_ACCESS_KEY environment variables.
    at Object.default_1 [as default] (D:\TestCafe\testcafe_tiki\node_modules\testcafe-browser-provider-browserstack\lib\utils\request-api.js:42:15)
    at JSTestingBackend.getBrowsersList (D:\TestCafe\testcafe_tiki\node_modules\testcafe-browser-provider-browserstack\lib\backends\js-testing.js:60:56)
    at BrowserProviderPluginHost._getDeviceList (D:\TestCafe\testcafe_tiki\node_modules\testcafe-browser-provider-browserstack\lib\index.js:77:49)
    at BrowserProviderPluginHost.init (D:\TestCafe\testcafe_tiki\node_modules\testcafe-browser-provider-browserstack\lib\index.js:208:20)
    at BrowserProvider.init (D:\TestCafe\testcafe_tiki\node_modules\testcafe\lib\browser\provider\index.js:187:14)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Proxy.getProvider (D:\TestCafe\testcafe_tiki\node_modules\testcafe\lib\browser\provider\pool.js:117:13)
    at async listBrowsers (D:\TestCafe\testcafe_tiki\node_modules\testcafe\lib\cli\cli.js:109:22)
    at async cli (D:\TestCafe\testcafe_tiki\node_modules\testcafe\lib\cli\cli.js:133:13)

I have done below configurations:
1.Installed testcafe (both global and local)
2.Installed testcafe-browser-provider-browserstack (both local and global).
3.Added BrowserStack username and access key to environment variables BROWSERSTACK_USERNAME and BROWSERSTACK_ACCESS_KEY under System Variables in Environment Variables option.

![testcafe-issue](https://user-images.githubusercontent.com/67421678/146651115-1fac80a1-faf0-49dd-aeb1-8e275c24a10a.JPG)

**Comment by AlexKamaev** [comment]
We usually do not have any errors with Authentication in Browserstack. As I understand, you are working on Windows. Please try to set the environment variables in your CMD.EXE as follows:


![image](https://user-images.githubusercontent.com/1678902/146890483-182610f7-a866-4f5f-bf22-85b6208b3533.png)

 

You can also check if you set a variable correctly using the following command:
```echo %BROWSERSTACK_USERNAME%```
Then, please run your testcafe command in this CMD window.
