### ISSUE TITLE
API error 13: Automate testing time expired.

### ISSUE THREAD

**Issue by Esteban26** [DevExpress/testcafe-browser-provider-browserstack#66]
@AndreyBelym I'm facing this issue issue, even if I set the BROWSERSTACK_USERNAME and BROWSERSTACK_ACCESS_KEY I'm getting this error while trying to run my tests on browserstack

If I run this command line I'm able to see the aliases in the console.

BROWSERSTACK_USERNAME=username BROWSERSTACK_ACCESS_KEY=accesskey testcafe -b browserstack

but with this command line I'm getting an the issue.
_______________________________________________________
`BROWSERSTACK_USERNAME=username BROWSERSTACK_ACCESS_KEY=access_key testcafe "--app" "node test/serve.js" "browserstack:Chrome@53.0:Windows 10" "test/spec/*.spec.ts"`
_______________________________________________________
`Error: API error 13: Automate testing time expired.
at /Users/username/Documents/HD/project/project/node_modules/testcafe-browser-provider-browserstack/lib/backends/automate.js:129:36
at invokeCallback (/Users/username/Documents/HD/project/project/node_modules/pinkie/index.js:60:12)
at Array.forEach (<anonymous>)
at publish (/Users/username/Documents/HD/project/project/node_modules/pinkie/index.js:147:32)
at Array.publishFulfillment (/Users/username/Documents/HD/project/project/node_modules/pinkie/index.js:152:2)
at Immediate.asyncFlush (/Users/username/Documents/HD/project/project/node_modules/pinkie/index.js:17:19)
at runCallback (timers.js:706:11)
at tryOnImmediate (timers.js:676:5)
at processImmediate (timers.js:658:5)
at process.topLevelDomainCallback (domain.js:121:23)`
Node version v10.13.0
Test cafe version 0.22.0

**Comment by fgordillo** [comment]
Hi Esteban, would you mind to give us more details about what you found out?
I'm trying to debug the same problem.

**Comment by Esteban26** [comment]
Hi @fgordillo, in my case issue was caused because we finished the free trial mins that browserstack offers  for automated testing (100 mins), so  we had to buy a plan to continue testing. But issue could be caused if user name or access key are not set at the env vars or they are wrong.

I had some problems while setting my env vars but I tried with this command line after upgrading our browserstack account and it worked... Note that the last part is used to run our webserver... so you may need to modify it.

BROWSERSTACK_USERNAME=user BROWSERSTACK_ACCESS_KEY=access_key testcafe  "-S" "-s" "artifacts/screenshots" "-p" "${USERAGENT}\${FIXTURE}_${TEST}.png" "browserstack:chrome@71.0:OS X High Sierra" "test/spec/*.spec.ts" "--app" "node test/serve.js" "--hostname" "localhost" "--app" "node test/serve.js" "--speed" "1"
