### ISSUE TITLE
 Error in Role initializer when running on browserstack Windows machines

### ISSUE THREAD

**Issue by wjcheng1** [DevExpress/testcafe-browser-provider-browserstack#73]
I keep getting this "Error in Role initializer " js error when running in Chrome, Edge on Windows using Browserstack.  When I ran the same test in Mac it was fine and when I run the test manually on Browserstack there's also no js errors.    

```
JavaScript error details:
      TypeError: Object expected
         at r.sendServiceMsg (http://172.16.0.152:50065/hammerhead.js:7:23733)
         at d (http://172.16.0.152:50065/hammerhead.js:6:14894)
```

userRoles.ts:
```
export const regular = Role(config.pageUrl, async (t) => {
  await lp.switchLoginIframe();
  await lp.login(config.user, config.password, false);
  await t.switchToMainWindow();
});

export const admin = Role(config.pageUrl, async (t) => {
  await lp.switchLoginIframe();
  await lp.login(config.admin, config.adminpassword, false);
  await t.switchToMainWindow();
});
```

loginPage.ts:
```
async login(username:string, password:string, remember:boolean) {
    await t
      .typeText(this.username, username)
      .typeText(this.password, password);
    if (remember) {
      await t.click(this.rememberMe);
    }

    await t.click(this.loginBtn);
  }
```

login_test.ts:
```
const users = [
  { name: 'Admin User', type: admin },
  { name: 'Regular User', type: regular }];

for (const user of users) {
  test
  .meta({ level: 'sanity' })(`Valid ${user.name} login`, async (t) => {
    await t.useRole(user.type);
    await t
    .expect(Selector('i.icon.icon-Logout---med').visible).ok();
  });
}
```

**Comment by miherlosev** [comment]
This error is not related to the `testcafe-browser-stack` module. Please create a separate [issue](https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md) in the TestCafe repository and provide all necessary information.
